server:
  port: 8082

spring:
  jpa:
    database: mysql
    show-sql: true
#    hibernate:
#      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfe
    username: root
    password: root

logging:
  level:
    org.springframework.web: DEBUG
    ma.pfe: DEBUG